import jsPDF from 'jspdf';

export const generateFraudReport = (prediction, selectedFile) => {
  const pdf = new jsPDF();
  
  // Add title
  pdf.setFontSize(20);
  pdf.setTextColor(40, 40, 40);
  pdf.text('Fraud Detection Analysis Report', 20, 30);
  
  // Add subtitle
  pdf.setFontSize(12);
  pdf.setTextColor(80, 80, 80);
  pdf.text(`Generated on: ${new Date().toLocaleString()}`, 20, 40);
  
  // Add image info
  pdf.setFontSize(14);
  pdf.setTextColor(40, 40, 40);
  pdf.text('Image Information', 20, 60);
  
  pdf.setFontSize(11);
  pdf.setTextColor(60, 60, 60);
  pdf.text(`File Name: ${selectedFile.name}`, 25, 70);
  pdf.text(`File Size: ${(selectedFile.size / 1024 / 1024).toFixed(2)} MB`, 25, 80);
  
  // Add prediction results
  pdf.setFontSize(14);
  pdf.setTextColor(40, 40, 40);
  pdf.text('Analysis Results', 20, 100);
  
  // Prediction
  pdf.setFontSize(16);
  const predictionColor = prediction.prediction === 'FRAUD' ? [255, 0, 0] : [0, 128, 0];
  pdf.setTextColor(...predictionColor);
  pdf.text(`Prediction: ${prediction.prediction}`, 25, 115);
  
  pdf.setFontSize(12);
  pdf.setTextColor(60, 60, 60);
  pdf.text(`Confidence: ${prediction.confidence}%`, 25, 125);
  
  // Risk level
  pdf.text(`Risk Level: ${prediction.riskLevel}`, 25, 135);
  
  // Probabilities
  pdf.text('Probability Breakdown:', 25, 150);
  pdf.text(`• Fraud Probability: ${prediction.fraudProbability}%`, 30, 160);
  pdf.text(`• Non-Fraud Probability: ${prediction.nonFraudProbability}%`, 30, 170);
  
  // Recommended action
  pdf.setFontSize(14);
  pdf.setTextColor(40, 40, 40);
  pdf.text('Recommended Action', 20, 190);
  
  pdf.setFontSize(11);
  pdf.setTextColor(60, 60, 60);
  const lines = pdf.splitTextToSize(prediction.recommendedAction, 160);
  pdf.text(lines, 25, 200);
  
  // Model information
  pdf.setFontSize(14);
  pdf.setTextColor(40, 40, 40);
  pdf.text('Model Information', 20, 230);
  
  pdf.setFontSize(11);
  pdf.setTextColor(60, 60, 60);
  pdf.text('Model: Fast Precision EfficientNet-B1', 25, 240);
  pdf.text('Precision: 87.9%', 25, 250);
  pdf.text('Recall: 86.0%', 25, 260);
  pdf.text('Accuracy: 91.4%', 25, 270);
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(120, 120, 120);
  pdf.text('Generated by FraudGuard AI - Insurance Fraud Detection System', 20, 280);
  
  // Save the PDF
  const fileName = `fraud-analysis-${selectedFile.name.split('.')[0]}-${Date.now()}.pdf`;
  pdf.save(fileName);
  
  return fileName;
};